#!/usr/bin/env python3
import blessed
import sys
term = blessed.Terminal()
last = None
count = 1
for line in sys.stdin:
    line = line.rstrip()
    if line == last:
        count += 1
        print(term.move_up(2) + term.move_x(0))
    else:
        last = line
        count = 1
    if count > 1:
        print(line, f'[{count}]', flush=True)
    else:
        print(line, flush=True)
